# Generated by cpp11: do not edit by hand

dust_sirs_alloc <- function(r_pars, pars_multi, step, n_particles, n_threads, r_seed) {
  .Call(`_sirs6f27933f_dust_sirs_alloc`, r_pars, pars_multi, step, n_particles, n_threads, r_seed)
}

dust_sirs_run <- function(ptr, step_end, device) {
  .Call(`_sirs6f27933f_dust_sirs_run`, ptr, step_end, device)
}

dust_sirs_simulate <- function(ptr, step_end) {
  .Call(`_sirs6f27933f_dust_sirs_simulate`, ptr, step_end)
}

dust_sirs_set_index <- function(ptr, r_index) {
  .Call(`_sirs6f27933f_dust_sirs_set_index`, ptr, r_index)
}

dust_sirs_set_state <- function(ptr, r_state, r_step) {
  .Call(`_sirs6f27933f_dust_sirs_set_state`, ptr, r_state, r_step)
}

dust_sirs_reset <- function(ptr, r_pars, step) {
  .Call(`_sirs6f27933f_dust_sirs_reset`, ptr, r_pars, step)
}

dust_sirs_state <- function(ptr, r_index) {
  .Call(`_sirs6f27933f_dust_sirs_state`, ptr, r_index)
}

dust_sirs_step <- function(ptr) {
  .Call(`_sirs6f27933f_dust_sirs_step`, ptr)
}

dust_sirs_reorder <- function(ptr, r_index) {
  invisible(.Call(`_sirs6f27933f_dust_sirs_reorder`, ptr, r_index))
}

dust_sirs_resample <- function(ptr, r_weights) {
  .Call(`_sirs6f27933f_dust_sirs_resample`, ptr, r_weights)
}

dust_sirs_set_pars <- function(ptr, r_pars) {
  .Call(`_sirs6f27933f_dust_sirs_set_pars`, ptr, r_pars)
}

dust_sirs_rng_state <- function(ptr, first_only) {
  .Call(`_sirs6f27933f_dust_sirs_rng_state`, ptr, first_only)
}

dust_sirs_set_rng_state <- function(ptr, rng_state) {
  .Call(`_sirs6f27933f_dust_sirs_set_rng_state`, ptr, rng_state)
}

dust_sirs_set_data <- function(ptr, data) {
  .Call(`_sirs6f27933f_dust_sirs_set_data`, ptr, data)
}

dust_sirs_compare_data <- function(ptr) {
  .Call(`_sirs6f27933f_dust_sirs_compare_data`, ptr)
}

dust_sirs_filter <- function(ptr, save_history) {
  .Call(`_sirs6f27933f_dust_sirs_filter`, ptr, save_history)
}

dust_sirs_capabilities <- function() {
  .Call(`_sirs6f27933f_dust_sirs_capabilities`)
}

dust_sirs_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_sirs6f27933f_dust_sirs_set_n_threads`, ptr, n_threads))
}

dust_sirs_n_state <- function(ptr) {
  .Call(`_sirs6f27933f_dust_sirs_n_state`, ptr)
}
