## Generated by dust (version 0.4.13) - do not edit
sir <- R6::R6Class(
  "dust",
  cloneable = FALSE,

  private = list(
    data_ = NULL,
    index_ = NULL,
    info_ = NULL,
    n_threads_ = NULL,
    ptr_ = NULL,

    simulate = function(steps, data, state, index = NULL,
                        n_threads = 1L, seed = NULL) {
      dust_sir_simulate(steps, data, state, index, n_threads, seed)
    }
  ),

  public = list(
    initialize = function(data, step, n_particles, n_threads = 1L,
                          seed = NULL) {
      res <- dust_sir_alloc(data, step, n_particles,
                        n_threads, seed)
      private$data_ <- data
      private$n_threads_ <- n_threads
      private$ptr_ <- res[[1L]]
      private$info_ <- res[[2L]]
    },

    name = function() {
      "sir"
    },

    run = function(step_end) {
      m <- dust_sir_run(private$ptr_, step_end)
      rownames(m) <- names(private$index_)
      m
    },

    set_index = function(index) {
      dust_sir_set_index(private$ptr_, index)
      private$index_ <- index
      invisible()
    },

    index = function() {
      private$index_
    },

    n_threads = function() {
      private$n_threads_
    },

    set_state = function(state, step = NULL) {
      dust_sir_set_state(private$ptr_, state, step)
    },

    reset = function(data, step) {
      private$info_ <- dust_sir_reset(private$ptr_, data, step)
      private$index_ <- NULL
      private$data_ <- data
      invisible()
    },

    state = function(index = NULL) {
      m <- dust_sir_state(private$ptr_, index)
      rownames(m) <- names(index)
      m
    },

    step = function() {
      dust_sir_step(private$ptr_)
    },

    reorder = function(index) {
      dust_sir_reorder(private$ptr_, as.integer(index))
      invisible()
    },

    info = function() {
      private$info_
    },

    data = function() {
      private$data_
    },

    rng_state = function(first_only = FALSE) {
      dust_sir_rng_state(private$ptr_, first_only)
    },

    set_rng_state = function(rng_state) {
      dust_sir_set_rng_state(private$ptr_, rng_state)
      invisible()
    },

    has_openmp = function() {
      dust_sir_has_openmp()
    }
  ))
## Generated by odin.dust (version 0.0.10) - do not edit
sir$set("public", "transform_variables", function(y) {
    info <- self$info()
    set_dim <- function(x, dimx) {
        if (length(dimx) > 1L) {
            dim(x) <- dimx
        }
        x
    }
    if (is.matrix(y)) {
        n <- ncol(y)
        Map(function(i, d) set_dim(y[i, , drop = FALSE], c(d,
            n)), info$index, info$dim)
    } else if (is.array(y)) {
        n <- dim(y)[2:3]
        Map(function(i, d) set_dim(y[i, , , drop = FALSE], c(d,
            n)), info$index, info$dim)
    } else {
        Map(function(i, d) set_dim(y[i], d), info$index, info$dim)
    }
})
